### PR TITLE
Add missing text-domain

### PR DESCRIPTION
**Pull request by alexclassroom**
Add these missing text-domain let related strings display correctly.

### CODE REVIEW

**Comment by 5um17** [comment]
Hi,

Thanks for the PR! 
I found these strings left without domain deliberately, So these strings can be translated using WP translation file. e.g. [Search &hellip;](https://translate.wordpress.org/projects/wp/dev/de/default/?filters%5Bterm%5D=Search+%26hellip%3B&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc)
However, there is one string `Setting Name:` that should be adjusted as no translation exist for this in WP core.

Could you please adjust the PR?

Thanks

**Comment by alexclassroom** [comment]
If NOT adding these missing text-domain, related UI strings can't be displayed correctly.
Missing-Text-Domain
I also found some strings can be localized, will submit new PR.

**Comment by alexclassroom** [comment]
If there are strings in your plugin that are also used in WordPress core (e.g. ‘Settings’), you should still add your own text domain to them, otherwise they’ll become untranslated if the core string changes (which happens).
Please refer the following link:
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#add-text-domain-to-strings

**Comment by 5um17** [comment]
Yes I know that but the reason is, it is exact copy of core code to keep the same default output. I have to keep the sync of strings if something changes. Still, I see this is standard so we have to follow. 

I also found the placeholder strings has issue, those are not translated not because of missing domain but because of early loading of strings. That should be fixed with plugin text domain and I will test and adjust the code if needed.

Thank you very much for your contribution!

**Pull request merged**
